<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="5 Thermal Regimes of Streams | BI 328 Conservation Biology" />
<meta property="og:type" content="book" />




<meta name="author" content="Labmanual Fall 2022" />

<meta name="date" content="2022-10-22" />


<meta name="description" content="5 Thermal Regimes of Streams | BI 328 Conservation Biology">

<title>5 Thermal Regimes of Streams | BI 328 Conservation Biology</title>

<link href="libs/tufte-css/tufte.css" rel="stylesheet" />
<link href="libs/tufte-css/envisioned.css" rel="stylesheet" />
<link href="libs/msmb-css/msmb.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }

code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>



<link rel="stylesheet" href="msmb.css" type="text/css" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}

}
</script>
<script>
function copy_link(id) {
  var dummy = document.createElement('input'),
  text = window.location.href.split(/[?#]/)[0] + '#' + id;
  document.body.appendChild(dummy);
  dummy.value = text;
  dummy.select();
  document.execCommand('copy');
  document.body.removeChild(dummy);
  
  var tooltip = document.getElementById(id + '-tooltip');
  tooltip.innerHTML = 'Copied!';
}

function reset_tooltip(id) {
  var tooltip = document.getElementById(id);
  tooltip.innerHTML = 'Copy link';
}
</script>

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul class="navbar">
<li class="msmb"><p class="title">BI 328 Conservation Biology<p><p class="author">Labmanual Fall 2022</p>
<li class="dropdown" style="float:right">
<a href="javascript:void(0)" class="dropbtn">&#x25BE; Chapters</a>
<div class="dropdown-content">
<a href="index.html" id="toc-overview">Overview</a>
<a href="installing-rrstudio.html" id="toc-installing-rrstudio"><span class="toc-section-number">1</span> Installing R/Rstudio</a>
<a href="project-management-and-rmarkdown-basics.html" id="toc-project-management-and-rmarkdown-basics"><span class="toc-section-number">2</span> Project management and Rmarkdown Basics</a>
<a href="restoration-ecology-of-temperature-grasslands.html" id="toc-restoration-ecology-of-temperature-grasslands"><span class="toc-section-number">3</span> Restoration Ecology of Temperature Grasslands</a>
<a href="iucn-redlist-quantifying-species-risk-levels.html" id="toc-iucn-redlist-quantifying-species-risk-levels"><span class="toc-section-number">4</span> IUCN Redlist: Quantifying species Risk Levels</a>
<a id="active-page" href="thermal-regimes-of-streams.html" id="toc-thermal-regimes-of-streams"><span class="toc-section-number">5</span> Thermal Regimes of Streams</a><ul class="toc-sections">
<li class="toc"><a href="#headwater-streams"> Headwater Streams</a></li>
<li class="toc"><a href="#identify-metrics-to-characterize-the-thermal-regime-of-streams"> Identify Metrics to characterize the thermal regime of streams</a></li>
<li class="toc"><a href="#temporal-variability-of-a-thermal-landscape-impacts-the-ecoystem-due-to-physiological-reactions-at-an-organismal-level"> Temporal variability of a thermal landscape impacts the ecoystem due to physiological reactions at an organismal level</a></li>
<li class="toc"><a href="#spatial-variability-within-a-thermal-landscape-allows-aquatic-organisms-to-maximize-growth-and-survival"> Spatial variability within a thermal landscape allows aquatic organisms to maximize growth and survival</a></li>
</ul>
<a href="references.html" id="toc-references">References</a>
</div>
</li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="thermal-regimes-of-streams" class="section level1" number="5">
<h1>
<span class="header-section-number">5</span> Thermal Regimes of Streams</h1>
<p><strong>Learning Objectives</strong></p>
<p>After completing this activity you should be able to</p>
<ul>
<li>Describe the thermal regime of a stream using a wide range of metrics to describe magnitude, frequency, duration, rate of change, timing, and variability of temperature.</li>
<li>Use an example to explain how temperature variability impacts an ecosystem due to physiological reactions at an organismal level</li>
<li>Distinguish between continuous/categorical (qualitative/quantitative) data</li>
<li>Use data visualizations to better understand a data set and identify patterns.</li>
<li>Use ggplot to create line plots to visualize quantitative trends over time.</li>
<li>Use descriptive statistics to summarize, organize, and compare basic features of a data set across time periods (and sites).</li>
<li>Use <code>group_by()</code> and <code>summarize()</code> to calculate summary statistics.</li>
<li>Choose an appropriate metric to answer a specific biological/ecological question.</li>
</ul>
<p>For each of our modules we will have a project-folder with an <code>Rproject</code>, <code>*.Rmd</code>-files, and sub-directories for data, scripts, and results as described in our <code>Rproject</code> Tutorial. You should create a directory on your Desktop or Documents folder on your laptop (name it something like <code>BI328</code>) as a home directory for all of our project folders this semester.</p>
<p>Download the <a href="https://drive.google.com/drive/folders/1p1xmqYx5964pSyStLZJ-isiWSAnyQL9g?usp=sharing">ThermalRegimes</a> project folder. Once you have downloaded it, unzip the project directory into your <code>BI328</code> directory. You can open the <code>Rproj</code> for this module either by double clicking on it which will launch <code>Rstudio</code> or by opening <code>Rstudio</code> and then using <code>File &gt; Open Project</code> or by clicking on the <code>Rproject</code> icon in the top right of your program window and selecting <code>Open Project</code>.</p>
<p>Once you have opened a project you should see the project name in the top right corner<label for="tufte-sn-1" class="margin-toggle sidenote-number">1</label><input type="checkbox" id="tufte-sn-1" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">1</span> Pro tip: If you run into issues where an Rmarkdown won’t render or file paths aren’t working (especially if things were working previously) one of your first steps should be to double check that the correct <code>Rproj</code> is loaded.</span>.</p>
<p>You should have a <code>ThermalRegimes.Rmd</code> in your project directory. Use that file to work through this lab - you will hand in your rendered (“knitted”) <code>html</code>-file as your homework assignment. So, first thing in the <code>YAML</code> header, change the author to your name. You will use this <code>Rmarkdown</code> file to record your answers.</p>
<p>We will need to install an additional package before we get started.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thermal-regimes-of-streams.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"lubridate"</span>)</span></code></pre></div>
<p>Before we get started load the <code>R packages</code> we will need to run our analysis<label for="tufte-sn-2" class="margin-toggle sidenote-number">2</label><input type="checkbox" id="tufte-sn-2" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">2</span> Remember, anytime you close <code>Rstudio</code> or quite an <code>R session</code> you need to reload your libraries, even if you you already have objects in your environment from the previous session</span>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="thermal-regimes-of-streams.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load libraries</span></span>
<span id="cb2-2"><a href="thermal-regimes-of-streams.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="thermal-regimes-of-streams.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb2-4"><a href="thermal-regimes-of-streams.html#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-5"><a href="thermal-regimes-of-streams.html#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="thermal-regimes-of-streams.html#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># load custom ggplot themes</span></span>
<span id="cb2-7"><a href="thermal-regimes-of-streams.html#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"scr/ggplot.R"</span>)</span></code></pre></div>
<div id="headwater-streams" class="section level2" number="5.1">
<h2>
<span class="header-section-number">5.1</span> Headwater Streams<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('headwater-streams')" onmouseout="reset_tooltip('headwater-streams-tooltip')"><span class="tooltiptext" id="headwater-streams-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>We are going to spend the next few labs exploring various aspects of headwater streams. Before lab you should have used this <a href="https://extension.unh.edu/resource/headwater-streams">description</a> to get a broad overview.</p>
<div id="ques:therm-1" class="question">
<p class="question-begin">
► Question 1
</p>
<div class="question-body">
<p>
Use the information from the brochure to list 4-5 key characteristics for each of the four major categories. Consider how dynamic each system is, whether you think it is a more/less homogenous habitat, how dynamic it is, what the main water source is, differences in terms of stream biota (plants and animals), and what sets is apart from the other types.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<ol style="list-style-type: decimal">
<li>Mountain Streams</li>
<li>Valley Streams</li>
<li>Spring-fed Brooks</li>
<li>Warm Rocky Streams</li>
</ol>
<div id="ques:therm-2" class="question">
<p class="question-begin">
► Question 2
</p>
<div class="question-body">
<p>
Headwater streams provide rich habitats for a wide range of species. Use the concepts of temporal and spatial turnover to explain why they support such species-rich biological communities (5-10 sentences).
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>Like most ecosystems, headwater streams are expected to be impacted by climate change. You will find a more in depth description of the points made in the brief introduction you read in this <a href="https://extension.unh.edu/sites/default/files/migrated_unmanaged_files/Resource004598_Rep6559.pdf">Amendment to the NH Wildlife Action Plan</a>.</p>
<div id="ques:therm-3" class="question">
<p class="question-begin">
► Question 3
</p>
<div class="question-body">
<p>
Briefly outline two central challenges, describing both the change in environmental conditions, how you expect this to affect the biological community, and what strategies can be used to help minimize this impact.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers
</p>
<div class="solution-body">
<ol style="list-style-type: decimal">
<li>Challenge One:
<ul>
<li>Outline challenge</li>
<li>impact on abiotic/biotic components of ecosystem</li>
<li>strategies to overcome</li>
</ul>
</li>
<li>Challenge Two:
<ul>
<li>Outline challenge</li>
<li>impact on abiotic/biotic components of ecosystem</li>
<li>strategies to overcome</li>
</ul>
</li>
</ol>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="identify-metrics-to-characterize-the-thermal-regime-of-streams" class="section level2" number="5.2">
<h2>
<span class="header-section-number">5.2</span> Identify Metrics to characterize the thermal regime of streams<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('identify-metrics-to-characterize-the-thermal-regime-of-streams')" onmouseout="reset_tooltip('identify-metrics-to-characterize-the-thermal-regime-of-streams-tooltip')"><span class="tooltiptext" id="identify-metrics-to-characterize-the-thermal-regime-of-streams-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<div id="ques:therm-4" class="question">
<p class="question-begin">
► Question 4
</p>
<div class="question-body">
<p>
Stream biodiversity is closely linked to temperature through thermally-mediated ecological processes at all hierarchical levels. For each levels describe 2-3 factors that could be impacted by temperature.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers
</p>
<div class="solution-body">
<ol style="list-style-type: decimal">
<li>At an organismal level, temperature [<em>2-3 factors potentially impacted by temperature</em>]</li>
<li>At the population level, temperature [<em>2-3 factors potentially impacted by temperature</em>]</li>
<li>At the community level, temperature [<em>2-3 factors potentially impacted by temperature</em>]</li>
</ol>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>Arguably, temperature is one of the primary determinants of aquatic ecosystems. The <strong>water temperature</strong> is a single value that describes the state at a specific point in time in space and is generally measured in degrees Celsius. By contrast, the <strong>thermal regime</strong> of a stream consists of a time series describing the water temperature over time in a single locations, frequently this data set will comprise the annual regular sequence of water temperature at specific locations that are continuously monitored.</p>
<p>Let’s take a look at some real data from Back Mountain Brook (<code>BMB</code>).</p>
<div id="exploring-temperature-data-sets" class="section level3" number="5.2.1">
<h3>
<span class="header-section-number">5.2.1</span> Exploring temperature data sets<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('exploring-temperature-data-sets')" onmouseout="reset_tooltip('exploring-temperature-data-sets-tooltip')"><span class="tooltiptext" id="exploring-temperature-data-sets-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>Let’s take a look at some real data from Back Mountain Brook (BMB) which is a headwater stream in southern New Hampshire.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="thermal-regimes-of-streams.html#cb3-1" aria-hidden="true" tabindex="-1"></a>BMB <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"data/BMB_water.txt"</span>, <span class="at">delim =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>,</span>
<span id="cb3-2"><a href="thermal-regimes-of-streams.html#cb3-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">col_types =</span> <span class="st">'cnn'</span>)</span></code></pre></div>
<div id="ques:therm-5" class="question">
<p class="question-begin">
► Question 5
</p>
<div class="question-body">
<p>
Take a quick look at the data frame you just read into R. The data you are looking at is what is generally described as raw data. These are the individual measurements that have not been summarized, processed, or analyzed in any way. Scroll through the individual rows amd briefly describe what information you can glean.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers
</p>
<div class="solution-body">
<ul>
<li>what variables do you have?</li>
<li>what is being measured?</li>
<li>what are units being used?</li>
<li>what is the resolution of your data?</li>
<li>what is the time frame?</li>
<li>what is the spatial extent?</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>Currently, all of our date and time information is in a single column, we are going to split that information into individual columns.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="thermal-regimes-of-streams.html#cb4-1" aria-hidden="true" tabindex="-1"></a>BMB <span class="ot">&lt;-</span> BMB <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="thermal-regimes-of-streams.html#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date_Time =</span> <span class="fu">parse_date_time</span>(Date_Time, <span class="at">orders =</span> <span class="st">"mdyHM"</span>),</span>
<span id="cb4-3"><a href="thermal-regimes-of-streams.html#cb4-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">Date =</span> <span class="fu">as_date</span>(Date_Time),</span>
<span id="cb4-4"><a href="thermal-regimes-of-streams.html#cb4-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Day =</span> <span class="fu">day</span>(Date_Time),</span>
<span id="cb4-5"><a href="thermal-regimes-of-streams.html#cb4-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Month =</span> <span class="fu">month</span>(Date_Time),</span>
<span id="cb4-6"><a href="thermal-regimes-of-streams.html#cb4-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">Year =</span> <span class="fu">year</span>(Date_Time),</span>
<span id="cb4-7"><a href="thermal-regimes-of-streams.html#cb4-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">Hour =</span> <span class="fu">hour</span>(Date_Time))</span></code></pre></div>
<p>Variables can be classified as either continuous, discrete, or categorical. <strong>Categorical</strong> variables have finite number of discrete groups that may or may not have a logical order. Similarly, <strong>discrete</strong> variables are numeric, with a countable number of values between any two given values. By contrast, <strong>continuous</strong> variables are variables with an infinite number of values between any two given values.</p>
<div id="ques:therm-6" class="question">
<p class="question-begin">
► Question 6
</p>
<div class="question-body">
<p>
Take another look at the dataframe and determine what category each variable falls under.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers
</p>
<div class="solution-body">
<ul>
<li>Categorical: Variable X, …</li>
<li>Continuous: Variable Y, …</li>
<li>Discrete: Variable Z, …</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>We defined a thermal regime as the regular pattern of the change in water temperature over time in a single location. Just by looking at the 52039 lines of data it can be very difficult to describe the temperature regime for this stream. Data visualizations can help us better understand the underlying data. We can use <strong>Exploratory plots</strong> to better understand the data and discover hidden patterns in a data set. Once we have completed our analysis and understand the data, we will generate <strong>Explanatory plots</strong> to clearly communicate our insights with others.</p>
<p>Let’s start by making a <strong>heatplot</strong> which uses color to code for the magnitude of individual values. This will allow us to visualize every single data point in the data set.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="thermal-regimes-of-streams.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(BMB, <span class="fu">aes</span>(<span class="at">y =</span> Hour, <span class="at">x =</span> Day, <span class="at">fill =</span> Water_Temp)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="thermal-regimes-of-streams.html#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="thermal-regimes-of-streams.html#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(Year <span class="sc">~</span> Month) <span class="sc">+</span></span>
<span id="cb5-4"><a href="thermal-regimes-of-streams.html#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">"inferno"</span>) <span class="sc">+</span></span>
<span id="cb5-5"><a href="thermal-regimes-of-streams.html#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_reverse</span>() <span class="sc">+</span></span>
<span id="cb5-6"><a href="thermal-regimes-of-streams.html#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-6"></span>
<p class="caption marginnote shownote">
Figure 5.1: Hourly water temperature for Back Mountain Brook (2014-2020).
</p>
<img src="_main_files/figure-html/unnamed-chunk-6-1.png" alt="Hourly water temperature for Back Mountain Brook (2014-2020)." width="864">
</div>
<div id="ques:therm-7" class="question">
<p class="question-begin">
► Question 7
</p>
<div class="question-body">
<p>
Our heatplot consists of individual panels of months in columns and years in rows. For each panel you can determine the temperature for every hour (y-axis) for each day (x-axis) by comparing the color of that tile to the scale at the bottom. Use the heatplot to identify major patterns in the data.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers<span id="sol-start-5" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"></span>
</p>
<div id="sol-body-5" class="solution-body" style="display: none;">
<ul>
<li>How does temperature change over time?</li>
<li>Are patterns consistent over a day? month? year?</li>
<li>Are there any outliers to the general patterns?</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="descriptive-statistics-to-summarizing-temperature-data" class="section level3" number="5.2.2">
<h3>
<span class="header-section-number">5.2.2</span> Descriptive statistics to summarizing temperature data<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('descriptive-statistics-to-summarizing-temperature-data')" onmouseout="reset_tooltip('descriptive-statistics-to-summarizing-temperature-data-tooltip')"><span class="tooltiptext" id="descriptive-statistics-to-summarizing-temperature-data-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>The heatplot helps us get a better overview of the data set compared to scrolling through all the rows of raw data, but it is still a lot of data points to be considering. Generally, we need to summarize the <strong>raw data</strong> using <strong>descriptive</strong> or <strong>summary statistics</strong><label for="tufte-sn-3" class="margin-toggle sidenote-number">3</label><input type="checkbox" id="tufte-sn-3" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">3</span> Descriptive statistics describe and quantify the basic features of a data set with the goal of being able to summarize, simplify, compare, and organize the contents.</span>.</p>
<div id="ques:therm-8" class="question">
<p class="question-begin">
► Question 8
</p>
<div class="question-body">
<p>
Start a list of metrics you could use to describe stream temperature of Back Mountain Brook. Try to be as specific as possible. Once you run out of ideas, compare notes with a few classmates around you and compile a single list of metrics. Discuss whether you can group them into categories based on what you have measured.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers<span id="sol-start-6" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"></span>
</p>
<div id="sol-body-6" class="solution-body" style="display: none;">
<ul>
<li>Category X:
<ul>
<li>metric</li>
<li>metric</li>
</ul>
</li>
<li>Category Y:
<ul>
<li>metric</li>
<li>metric</li>
</ul>
</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>We have previously used <code>R</code> to calculate fundamental descriptive statistics like the mean, standard deviation, minimum, and maximum temperature values using the functions <code>group_by()</code> and <code>summarize()</code>.</p>
<ul>
<li>
<code>group_by()</code> allows you specify one or more variables (columns) to group you data by. For example, if you want to calculate the annual mean temperature, you would group by year. Once you do this, <code>R</code> will treat each group as independent; you can think of this having taken your data frame and creating subsets of your data where each subset would be the temperature measurements of an entire year.</li>
<li>
<code>summarize()</code> allows you to specify a metric that you want to calculate. For example, we can use the function <code>mean()</code> to calcualte the mean.</li>
</ul>
<p>Let’s start by calculating the annual mean temperature:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="thermal-regimes-of-streams.html#cb6-1" aria-hidden="true" tabindex="-1"></a>annual_mean <span class="ot">&lt;-</span> BMB <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="thermal-regimes-of-streams.html#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="thermal-regimes-of-streams.html#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Water_Temp))</span></code></pre></div>
<p>Let’s take a look at what that new data set looks like:</p>
<p><!--
<caption>--><span class="marginnote shownote"><span id="tab:unnamed-chunk-8">Table 5.1: </span>Mean annual temperature Back Mountain Brook</span><!--</caption>--></p>
<table>
<thead><tr class="header">
<th align="right">Year</th>
<th align="right">mean</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">2014</td>
<td align="right">5.85</td>
</tr>
<tr class="even">
<td align="right">2015</td>
<td align="right">8.15</td>
</tr>
<tr class="odd">
<td align="right">2016</td>
<td align="right">8.46</td>
</tr>
<tr class="even">
<td align="right">2017</td>
<td align="right">7.89</td>
</tr>
<tr class="odd">
<td align="right">2018</td>
<td align="right">8.32</td>
</tr>
<tr class="even">
<td align="right">2019</td>
<td align="right">7.67</td>
</tr>
<tr class="odd">
<td align="right">2020</td>
<td align="right">8.80</td>
</tr>
</tbody>
</table>
<p>We can use the same syntax to calculate the standard deviation, minimum and maximum temperatures.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="thermal-regimes-of-streams.html#cb7-1" aria-hidden="true" tabindex="-1"></a>annual_stats <span class="ot">&lt;-</span> BMB <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="thermal-regimes-of-streams.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="thermal-regimes-of-streams.html#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Water_Temp),</span>
<span id="cb7-4"><a href="thermal-regimes-of-streams.html#cb7-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">std =</span> <span class="fu">sd</span>(Water_Temp),</span>
<span id="cb7-5"><a href="thermal-regimes-of-streams.html#cb7-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min =</span> <span class="fu">min</span>(Water_Temp),</span>
<span id="cb7-6"><a href="thermal-regimes-of-streams.html#cb7-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max =</span> <span class="fu">max</span>(Water_Temp))</span></code></pre></div>
<p>Let’s take a look at that new data set<label for="tufte-sn-4" class="margin-toggle sidenote-number">4</label><input type="checkbox" id="tufte-sn-4" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">4</span> Remember, a good description starts with a summary of the general patterns and then points out notable details. Note, a description does not interpret results, that usually occurs in the discussion.</span>.</p>
<p><!--
<caption>--><span class="marginnote shownote"><span id="tab:unnamed-chunk-10">Table 5.2: </span>Yearly mean, standard deviation, minimum and maximum temperature for Back Mountain Brook.</span><!--</caption>--></p>
<table>
<thead><tr class="header">
<th align="right">Year</th>
<th align="right">mean</th>
<th align="right">std</th>
<th align="right">min</th>
<th align="right">max</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">2014</td>
<td align="right">5.85</td>
<td align="right">3.62</td>
<td align="right">0.52</td>
<td align="right">15.82</td>
</tr>
<tr class="even">
<td align="right">2015</td>
<td align="right">8.15</td>
<td align="right">5.94</td>
<td align="right">0.05</td>
<td align="right">19.01</td>
</tr>
<tr class="odd">
<td align="right">2016</td>
<td align="right">8.46</td>
<td align="right">6.23</td>
<td align="right">0.05</td>
<td align="right">21.96</td>
</tr>
<tr class="even">
<td align="right">2017</td>
<td align="right">7.89</td>
<td align="right">5.94</td>
<td align="right">0.02</td>
<td align="right">19.41</td>
</tr>
<tr class="odd">
<td align="right">2018</td>
<td align="right">8.32</td>
<td align="right">7.28</td>
<td align="right">-5.08</td>
<td align="right">25.82</td>
</tr>
<tr class="even">
<td align="right">2019</td>
<td align="right">7.67</td>
<td align="right">6.47</td>
<td align="right">0.02</td>
<td align="right">24.27</td>
</tr>
<tr class="odd">
<td align="right">2020</td>
<td align="right">8.80</td>
<td align="right">6.96</td>
<td align="right">0.02</td>
<td align="right">21.70</td>
</tr>
</tbody>
</table>
<div id="ques:therm-9" class="question">
<p class="question-begin">
► Question 9
</p>
<div class="question-body">
<p>
Give a brief description of the summary statistics you just generated.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers<span id="sol-start-7" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"></span>
</p>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>When you are asked to give a brief description, this should involve a several sentences (exactly how many will depend on how complex the data is you are describing). The key is to be clear and specific, but not get lost in unnecessary details. You can follow a simple, standard outline - the key is to start with a statement about what is being described/summarized with that data set, then point out the general pattern(s), followed by notable highlights.</p>
<ul>
<li>What is being summarized/compared/described?<label for="tufte-sn-5" class="margin-toggle sidenote-number">5</label><input type="checkbox" id="tufte-sn-5" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">5</span> For example: <em>From 2014 - 2020 the yearly mean temperature ranged from 5.85 to 8.0°C in Rand Brook, with minimum temperatures around 0°C and maximum temperatures ranging from 15.8 - 25.82°C. With the exception of 2014 standard deviation is around 6-7°C.</em></span> As appropriate state time periods and/or locations analyzed, metrics/units used to measure. This statement will frequently also “bleed over” into stating general patterns</li>
<li>What is the general pattern?<label for="tufte-sn-6" class="margin-toggle sidenote-number">6</label><input type="checkbox" id="tufte-sn-6" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">6</span> For example: <em>There is no consistent trend of yearly mean temperatures increasing or decreasing over time</em></span> Go for general trends (ignore some of the small details our outlier values), remember: “no pattern” is also a pattern.</li>
<li>Are the notable details to be highlighted?<label for="tufte-sn-7" class="margin-toggle sidenote-number">7</label><input type="checkbox" id="tufte-sn-7" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">7</span> For example: <em>Maximum values are generally between 19 and 22°C, though notably in 2018 and 2019 values &gt;24°C were recorded.</em> this is interesting - even though there is no real trend in yearly means, clearly there are outlier years, especially in the context of our question of cold-water refugia the warmer years are of interest… so we point it out here for a later discussion</span>. This could include outlier values, components that are unexpected. Generally you would consider what your question is to determine what is relevant and you would keep in mind what your discussion points are going to be, even though at this point you should not be giving an interpretation of your data.</li>
<li>Is there something that should be pointed out to make sure that results are not presented in a misleading way? <label for="tufte-sn-8" class="margin-toggle sidenote-number">8</label><input type="checkbox" id="tufte-sn-8" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">8</span> For example: <em>Values for 2014 contain only a data from October - December, and 2020 only contains data until the beginning of August</em>. Pointing this out let’s the reader know that those values are difficult to compare to the other years… frankly the 2014 data should probably be excluded.</span>
</li>
</ul>
<p>Remember: For a description you should not be interpreting the data, e.g. by giving an explanation of how those patterns are being produced.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>By calculating descriptive stats at the annual level, you have collapsed all the temperature values for a single year into one number. This means that we are losing a lot of information.</p>
<div id="ques:therm-10" class="question">
<p class="question-begin">
► Question 10
</p>
<div class="question-body">
<p>
Use your new-found R skills to calculate monthly mean values. Consider that your data set contains more than one of each month when you group your data.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
► Solution<span id="sol-start-8" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"></span>
</p>
<div id="sol-body-8" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="thermal-regimes-of-streams.html#cb8-1" aria-hidden="true" tabindex="-1"></a>monthly_stats <span class="ot">&lt;-</span> BMB <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="thermal-regimes-of-streams.html#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Month) <span class="sc">%&gt;%</span>             <span class="co"># summarizing just by month would create summary stats across all years for each month</span></span>
<span id="cb8-3"><a href="thermal-regimes-of-streams.html#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Water_Temp),</span>
<span id="cb8-4"><a href="thermal-regimes-of-streams.html#cb8-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">std =</span> <span class="fu">sd</span>(Water_Temp),</span>
<span id="cb8-5"><a href="thermal-regimes-of-streams.html#cb8-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min =</span> <span class="fu">min</span>(Water_Temp),</span>
<span id="cb8-6"><a href="thermal-regimes-of-streams.html#cb8-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max =</span> <span class="fu">max</span>(Water_Temp))</span></code></pre></div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>Take a look at your summary stats. With the annual stats it was pretty straightforward to to compare values in a table - now you have a lot more values to look at. This is where a visualization might come in handy.</p>
</div>
<div id="visualizing-the-thermal-regime-of-a-stream" class="section level3" number="5.2.3">
<h3>
<span class="header-section-number">5.2.3</span> Visualizing the thermal regime of a stream<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('visualizing-the-thermal-regime-of-a-stream')" onmouseout="reset_tooltip('visualizing-the-thermal-regime-of-a-stream-tooltip')"><span class="tooltiptext" id="visualizing-the-thermal-regime-of-a-stream-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<div id="ques:therm-11" class="question">
<p class="question-begin">
► Question 11
</p>
<div class="question-body">
<p>
Consider how you might plot the monthly means to make it easier to discern the general pattern. Sketch out on a piece of paper what you think the figure will look like.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers
</p>
<div class="solution-body">
<ul>
<li>what should be on your x-axis?</li>
<li>what will be on your y-axis?</li>
<li>how many plots do you want?</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>Let’s learn how to use <code>R</code> to generate a few exploratory plots to visualize trends in our monthly means<label for="tufte-sn-9" class="margin-toggle sidenote-number">9</label><input type="checkbox" id="tufte-sn-9" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">9</span> The comments (<code>R</code> ignores anything that comes after a <code>#</code> which allows us to add comments to our code, this is a helpful process not only for other people trying to understand your code but future-you will also thank you when they try to remember what current-you was <del>plotting</del> thinking)</span>.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="thermal-regimes-of-streams.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(monthly_stats, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> mean)) <span class="sc">+</span>   <span class="co"># specify which object to plot, what should be on x and y axis</span></span>
<span id="cb9-2"><a href="thermal-regimes-of-streams.html#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>                                    <span class="co"># plot each value as a point</span></span>
<span id="cb9-3"><a href="thermal-regimes-of-streams.html#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">12</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span>   <span class="co"># plot values 1 - 12 (months) on x-axis</span></span>
<span id="cb9-4"><a href="thermal-regimes-of-streams.html#cb9-4" aria-hidden="true" tabindex="-1"></a>  theme_standard                                    <span class="co"># custom theme</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-12"></span>
<p class="caption marginnote shownote">
Figure 5.2: Mean monthly temperatures for Back Mountain Brook (2014-2020).
</p>
<img src="_main_files/figure-html/unnamed-chunk-12-1.png" alt="Mean monthly temperatures for Back Mountain Brook (2014-2020)." width="672">
</div>
<p>We can add a line that shows the general trend.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="thermal-regimes-of-streams.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(monthly_stats, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> mean)) <span class="sc">+</span>   <span class="co"># specify which object to plot, what should be on x and y axis</span></span>
<span id="cb10-2"><a href="thermal-regimes-of-streams.html#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>                                    <span class="co"># plot each value as a point</span></span>
<span id="cb10-3"><a href="thermal-regimes-of-streams.html#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span>                                   <span class="co"># add a trendline</span></span>
<span id="cb10-4"><a href="thermal-regimes-of-streams.html#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">12</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span>   <span class="co"># plot values 1 - 12 (months) on x-axis</span></span>
<span id="cb10-5"><a href="thermal-regimes-of-streams.html#cb10-5" aria-hidden="true" tabindex="-1"></a>  theme_standard</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-13"></span>
<p class="caption marginnote shownote">
Figure 5.3: Mean monthly temperatures for Back Mountain Brook (2014-2020). Blue line indicates trendline, grey area is 95% confidence interval
</p>
<img src="_main_files/figure-html/unnamed-chunk-13-1.png" alt="Mean monthly temperatures for Back Mountain Brook (2014-2020). Blue line indicates trendline, grey area is 95% confidence interval" width="672">
</div>
<p>We can also create individual line plots for every year.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="thermal-regimes-of-streams.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(monthly_stats, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> mean)) <span class="sc">+</span>   <span class="co"># specify which object to plot, what should be on x and y axis</span></span>
<span id="cb11-2"><a href="thermal-regimes-of-streams.html#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span>                                     <span class="co"># connect values with a line</span></span>
<span id="cb11-3"><a href="thermal-regimes-of-streams.html#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>                                    <span class="co"># plot each value as a point</span></span>
<span id="cb11-4"><a href="thermal-regimes-of-streams.html#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(. <span class="sc">~</span> Year) <span class="sc">+</span>                            <span class="co"># create individual plots per year</span></span>
<span id="cb11-5"><a href="thermal-regimes-of-streams.html#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">12</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span>   <span class="co"># plot values 1 - 12 (months) on x-axis</span></span>
<span id="cb11-6"><a href="thermal-regimes-of-streams.html#cb11-6" aria-hidden="true" tabindex="-1"></a>  theme_facet</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-14"></span>
<p class="caption marginnote shownote">
Figure 5.4: Mean monthly temperatures for Back Mountain Brook from 2014-2020.
</p>
<img src="_main_files/figure-html/unnamed-chunk-14-1.png" alt="Mean monthly temperatures for Back Mountain Brook from 2014-2020." width="672">
</div>
<p>Note how each plot is plotting the same information, but the different visualizations highlight different patterns. For example the first two plots make it easy to compare how similar mean temperatures is (or is not) for each month, while the last plot focuses on the regular pattern of change over time across years. This makes it easier to compare the shape of the plot for each year.</p>
<div id="ques:therm-12" class="question">
<p class="question-begin">
► Question 12
</p>
<div class="question-body">
<p>
Practice your new found data analysis skills by generating a dataset of daily mean, minimum, and maximum temperatures.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
► Solution<span id="sol-start-10" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"></span>
</p>
<div id="sol-body-10" class="solution-body" style="display: none;">
<p>The key to accomplishing this is in how you group the data. Grouping it just by <code>day</code> will create a data set mean temperatures across all “first days of the month” (across all months and years). This is not what we are looking for - we want each day of the year. The column <code>Date</code> is going to be much more helpful.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="thermal-regimes-of-streams.html#cb12-1" aria-hidden="true" tabindex="-1"></a>daily_stats <span class="ot">&lt;-</span> BMB <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="thermal-regimes-of-streams.html#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Date) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="thermal-regimes-of-streams.html#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Water_Temp),</span>
<span id="cb12-4"><a href="thermal-regimes-of-streams.html#cb12-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">std =</span> <span class="fu">sd</span>(Water_Temp),</span>
<span id="cb12-5"><a href="thermal-regimes-of-streams.html#cb12-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min =</span> <span class="fu">min</span>(Water_Temp),</span>
<span id="cb12-6"><a href="thermal-regimes-of-streams.html#cb12-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max =</span> <span class="fu">max</span>(Water_Temp))</span></code></pre></div>
<p>If you look at that data set, you see that now you only have the column for each day. This makes it straightforward to compare values for each day, but it would be difficult to group it for monthly or annual comparisons of distribution of values.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="thermal-regimes-of-streams.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(daily_stats)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   Date        mean   std   min   max
##   &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 2014-10-03 11.5  0.162 11.3   11.7
## 2 2014-10-04 11.6  0.445 11.1   12.5
## 3 2014-10-05 11.1  0.718  9.83  12.5
## 4 2014-10-06  9.85 0.650  8.97  10.6
## 5 2014-10-07 11.2  0.766 10.3   12.1
## 6 2014-10-08 12.2  0.297 11.5   12.7</code></pre>
<p>If you want to be able to do this, one option would be to include <code>Year</code> and <code>Month</code> as grouping values. You would still want to use <code>Date</code> instead of <code>Day</code> so that it is easier to plot values over time.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="thermal-regimes-of-streams.html#cb15-1" aria-hidden="true" tabindex="-1"></a>daily_stats <span class="ot">&lt;-</span> BMB <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="thermal-regimes-of-streams.html#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Month, Date) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="thermal-regimes-of-streams.html#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Water_Temp),</span>
<span id="cb15-4"><a href="thermal-regimes-of-streams.html#cb15-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">std =</span> <span class="fu">sd</span>(Water_Temp),</span>
<span id="cb15-5"><a href="thermal-regimes-of-streams.html#cb15-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min =</span> <span class="fu">min</span>(Water_Temp),</span>
<span id="cb15-6"><a href="thermal-regimes-of-streams.html#cb15-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max =</span> <span class="fu">max</span>(Water_Temp))</span></code></pre></div>
<p>The other option would be to group by <code>Date</code> and then just extract the information on Day, Month, and Year the same way we did when we initially read in the data set.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="thermal-regimes-of-streams.html#cb16-1" aria-hidden="true" tabindex="-1"></a>daily_stats <span class="ot">&lt;-</span> BMB <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="thermal-regimes-of-streams.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Date) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="thermal-regimes-of-streams.html#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Water_Temp),</span>
<span id="cb16-4"><a href="thermal-regimes-of-streams.html#cb16-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">std =</span> <span class="fu">sd</span>(Water_Temp),</span>
<span id="cb16-5"><a href="thermal-regimes-of-streams.html#cb16-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min =</span> <span class="fu">min</span>(Water_Temp),</span>
<span id="cb16-6"><a href="thermal-regimes-of-streams.html#cb16-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max =</span> <span class="fu">max</span>(Water_Temp)) <span class="sc">%&gt;%</span></span>
<span id="cb16-7"><a href="thermal-regimes-of-streams.html#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Day =</span> <span class="fu">day</span>(Date),</span>
<span id="cb16-8"><a href="thermal-regimes-of-streams.html#cb16-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">Month =</span> <span class="fu">month</span>(Date),</span>
<span id="cb16-9"><a href="thermal-regimes-of-streams.html#cb16-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">Year =</span> <span class="fu">year</span>(Date))</span></code></pre></div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div id="ques:therm-13" class="question">
<p class="question-begin">
► Question 13
</p>
<div class="question-body">
<p>
Practice your new found plot making skills by creating and additional 3-4 plots based on the various summary statistics you have calculated.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Suggestions<span id="sol-start-11" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"></span>
</p>
<div id="sol-body-11" class="solution-body" style="display: none;">
<p>A straightforward plot would be to look at the temperature change over time using mean, minimum, and/or maximum values.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="thermal-regimes-of-streams.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(daily_stats, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> mean)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="thermal-regimes-of-streams.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-3"><a href="thermal-regimes-of-streams.html#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">28</span>),             <span class="co"># define min/max for y-axis</span></span>
<span id="cb17-4"><a href="thermal-regimes-of-streams.html#cb17-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">breaks=</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">28</span>, <span class="at">by =</span> <span class="dv">2</span>)) <span class="sc">+</span>   <span class="co"># define increments</span></span>
<span id="cb17-5"><a href="thermal-regimes-of-streams.html#cb17-5" aria-hidden="true" tabindex="-1"></a>  theme_standard</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-19"></span>
<p class="caption marginnote shownote">
Figure 5.5: Mean daily temperature Back Mountain Brook (2014-2020).
</p>
<img src="_main_files/figure-html/unnamed-chunk-19-1.png" alt="Mean daily temperature Back Mountain Brook (2014-2020)." width="672">
</div>
<p>The advantage of coding your visualizations is that you can re-use code and just have to change one or two values to plot a different facet of the data. In the example above I added a line of code that sets the limits (min/max value) for the y-axis and then use the same range for the max plot which makes them easier to compare because they y-axes are identical.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="thermal-regimes-of-streams.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(daily_stats, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> max)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="thermal-regimes-of-streams.html#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-3"><a href="thermal-regimes-of-streams.html#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">28</span>),             <span class="co"># define min/max for y-axis</span></span>
<span id="cb18-4"><a href="thermal-regimes-of-streams.html#cb18-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">breaks=</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">28</span>, <span class="at">by =</span> <span class="dv">2</span>)) <span class="sc">+</span>   <span class="co"># define increments</span></span>
<span id="cb18-5"><a href="thermal-regimes-of-streams.html#cb18-5" aria-hidden="true" tabindex="-1"></a>  theme_standard</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-20"></span>
<p class="caption marginnote shownote">
Figure 5.6: Maximum daily temperature Back Mountain Brook (2014-2020).
</p>
<img src="_main_files/figure-html/unnamed-chunk-20-1.png" alt="Maximum daily temperature Back Mountain Brook (2014-2020)." width="672">
</div>
<p>This highlights the ranges and the general pattern of change over time (hot months, cold months, months with the most change). Another way to compare the daily values would be the distribution of daily means for each month using boxplots which are commonly used to compare distributions.</p>
<p>To do this we need to make sure that our Month and Year columns are categorical values. We can use the same function <code>lubridate::month</code> that we used previously to exact the month from a date but by setting <code>label = TRUE</code> we get the Month abbreviation instead of a number.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="thermal-regimes-of-streams.html#cb19-1" aria-hidden="true" tabindex="-1"></a>daily_stats <span class="ot">&lt;-</span> daily_stats <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="thermal-regimes-of-streams.html#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month =</span> <span class="fu">month</span>(Date, <span class="at">label =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-3"><a href="thermal-regimes-of-streams.html#cb19-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">Year =</span> <span class="fu">as.character</span>(Year))</span>
<span id="cb19-4"><a href="thermal-regimes-of-streams.html#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="thermal-regimes-of-streams.html#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(daily_stats, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> mean, <span class="at">color =</span> Year)) <span class="sc">+</span></span>
<span id="cb19-6"><a href="thermal-regimes-of-streams.html#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb19-7"><a href="thermal-regimes-of-streams.html#cb19-7" aria-hidden="true" tabindex="-1"></a>  theme_standard</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-21"></span>
<p class="caption marginnote shownote">
Figure 5.7: Distribution of mean daily temperature for each month by year.
</p>
<img src="_main_files/figure-html/unnamed-chunk-21-1.png" alt="Distribution of mean daily temperature for each month by year." width="672">
</div>
<p>An alternative to this plot would be a faceted plot, where we create individual plots per month with the distribution for each year. That makes comparisons for each month a little bit easier while our first plot emphasizes change over time<label for="tufte-sn-10" class="margin-toggle sidenote-number">10</label><input type="checkbox" id="tufte-sn-10" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">10</span> Note that I’ve added a line of code to rotate the x-axis labels to make it easier to read</span>.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="thermal-regimes-of-streams.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(daily_stats, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> mean)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="thermal-regimes-of-streams.html#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb20-3"><a href="thermal-regimes-of-streams.html#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Month) <span class="sc">+</span></span>
<span id="cb20-4"><a href="thermal-regimes-of-streams.html#cb20-4" aria-hidden="true" tabindex="-1"></a>  theme_standard <span class="sc">+</span></span>
<span id="cb20-5"><a href="thermal-regimes-of-streams.html#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="co"># turn x-axis labels 90 degrees</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-22"></span>
<p class="caption marginnote shownote">
Figure 5.8: Distribution of mean daily temperature for each month by year.
</p>
<img src="_main_files/figure-html/unnamed-chunk-22-1.png" alt="Distribution of mean daily temperature for each month by year." width="672">
</div>
<p>Another suggested plot was to look at monthly mean temperature in a way that makes it easy to compare those values across years using barplots.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="thermal-regimes-of-streams.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(monthly_stats, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> mean)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="thermal-regimes-of-streams.html#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb21-3"><a href="thermal-regimes-of-streams.html#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Month) <span class="sc">+</span></span>
<span id="cb21-4"><a href="thermal-regimes-of-streams.html#cb21-4" aria-hidden="true" tabindex="-1"></a>  theme_standard</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-23"></span>
<p class="caption marginnote shownote">
Figure 5.9: Comparison of mean monthly temperatures 2014-2020.
</p>
<img src="_main_files/figure-html/unnamed-chunk-23-1.png" alt="Comparison of mean monthly temperatures 2014-2020." width="672">
</div>
<p>Another version of this is what is called a lollipop plot, which uses a lot less ink but conveys the same information.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="thermal-regimes-of-streams.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(monthly_stats, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> mean)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="thermal-regimes-of-streams.html#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>( <span class="fu">aes</span>(<span class="at">x=</span> Year, <span class="at">xend =</span> Year, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">yend =</span> mean), <span class="at">color=</span><span class="st">"black"</span>) <span class="sc">+</span>  <span class="co"># create line instead of bar</span></span>
<span id="cb22-3"><a href="thermal-regimes-of-streams.html#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>                                                                 <span class="co"># place point at value</span></span>
<span id="cb22-4"><a href="thermal-regimes-of-streams.html#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Month) <span class="sc">+</span>                                                          <span class="co"># create individual plot per month</span></span>
<span id="cb22-5"><a href="thermal-regimes-of-streams.html#cb22-5" aria-hidden="true" tabindex="-1"></a>  theme_facet <span class="sc">+</span></span>
<span id="cb22-6"><a href="thermal-regimes-of-streams.html#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>))            <span class="co"># turn x-axis labels 90 degrees</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-24"></span>
<p class="caption marginnote shownote">
Figure 5.10: Comparison of mean monthly temperatures 2014-2020.
</p>
<img src="_main_files/figure-html/unnamed-chunk-24-1.png" alt="Comparison of mean monthly temperatures 2014-2020." width="672">
</div>
<p>Finally, we had a suggestion to look at how variability of temperature changes over the year using the standard deviation. One way to do this would be to look at the distribution within months using boxplots.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="thermal-regimes-of-streams.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(daily_stats, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> std)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="thermal-regimes-of-streams.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb23-3"><a href="thermal-regimes-of-streams.html#cb23-3" aria-hidden="true" tabindex="-1"></a>  theme_standard</span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-25"></span>
<p class="caption marginnote shownote">
Figure 5.11: Distribution of standard deviation of daily temperatures for each month.
</p>
<img src="_main_files/figure-html/unnamed-chunk-25-1.png" alt="Distribution of standard deviation of daily temperatures for each month." width="672">
</div>
<p>Splitting this up by year takes the emphasis away from the broad-scale pattern and allows us to identify individual years where variability is higher compared to others.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="thermal-regimes-of-streams.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(daily_stats, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> std)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="thermal-regimes-of-streams.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb24-3"><a href="thermal-regimes-of-streams.html#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Year) <span class="sc">+</span></span>
<span id="cb24-4"><a href="thermal-regimes-of-streams.html#cb24-4" aria-hidden="true" tabindex="-1"></a>  theme_standard <span class="sc">+</span></span>
<span id="cb24-5"><a href="thermal-regimes-of-streams.html#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>))            <span class="co"># turn x-axis labels 90 degrees</span></span></code></pre></div>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-26"></span>
<p class="caption marginnote shownote">
Figure 5.12: Distribution of standard deviation of daily temperatures for each month by year.
</p>
<img src="_main_files/figure-html/unnamed-chunk-26-1.png" alt="Distribution of standard deviation of daily temperatures for each month by year." width="672">
</div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div id="ques:therm-14" class="question">
<p class="question-begin">
► Question 14
</p>
<div class="question-body">
<p>
Pick two of the plots you have generated that you think best visualize the thermal regime of Back Mountain Brook and write a brief description of the data being shown, then discuss your results from both plots to describe the thermal regime of Back Mountain Brook.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers<span id="sol-start-12" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"></span>
</p>
<div id="sol-body-12" class="solution-body" style="display: none;">
<ul>
<li>Description figure 1: 5-7 sentences answering the following questions -
<ul>
<li>What is being summarized/compared/described?</li>
<li>What is the general pattern?</li>
<li>Are the notable details to be highlighted?</li>
<li>Is there something that should be pointed out to make sure that results are not presented in a misleading way?</li>
</ul>
</li>
<li>Description figure 2: 5-7 sentences answering the following questions -
<ul>
<li>What is being summarized/compared/described?</li>
<li>What is the general pattern?</li>
<li>Are the notable details to be highlighted?</li>
<li>Is there something that should be pointed out to make sure that results are not presented in a misleading way?</li>
</ul>
</li>
<li>Discussion of figure 1 and 2: Interpret the patterns you see, explain what factors could be driving temperatures to produce the patterns and notable details you highlighted. Make a connection between the information of the two plots.</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div id="ques:therm-15" class="question">
<p class="question-begin">
► Question 15
</p>
<div class="question-body">
<p>
Discuss with your lab mate whether we have fully characterized the thermal regime of our stream or if you can think of additional metrics that might be useful. You do not need to add a written summary of your conversation.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="a-wide-range-of-metrics-are-used-to-describe-the-thermal-regime-of-a-stream" class="section level3" number="5.2.4">
<h3>
<span class="header-section-number">5.2.4</span> A wide range of metrics are used to describe the thermal regime of a stream<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('a-wide-range-of-metrics-are-used-to-describe-the-thermal-regime-of-a-stream')" onmouseout="reset_tooltip('a-wide-range-of-metrics-are-used-to-describe-the-thermal-regime-of-a-stream-tooltip')"><span class="tooltiptext" id="a-wide-range-of-metrics-are-used-to-describe-the-thermal-regime-of-a-stream-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>We can group metrics describing the thermal regime of a stream into six categories: <strong>Magnitude</strong>, <strong>Frequency</strong>, <strong>Duration</strong>, <strong>Rate of change</strong>, <strong>Timing</strong>, and <strong>Variability</strong>.</p>
<div id="ques:therm-16" class="question">
<p class="question-begin">
► Question 16
</p>
<div class="question-body">
<p>
Take the list of metrics given to you on the whiteboard and work your class mates to define each category and assign metrics to each category in the table below.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>Now that we’ve thought more about individual facets of thermal regimes, let’s revisit the idea that stream biodiversity is closely linked to temperature through thermally-mediated ecological processes at all hierarchical levels.</p>
<div id="ques:therm-17" class="question">
<p class="question-begin">
► Question 17
</p>
<div class="question-body">
<p>
For each of the ecological facets below identify a metric describing the thermal regime that would impact it and add it to your table accordingly.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<ul>
<li>presence/absence of a species during certain time periods/locations</li>
<li>mortality</li>
<li>migration events</li>
<li>reproductive timing</li>
<li>individual stress</li>
<li>competitive advantage</li>
<li>metabolic demand</li>
<li>shifts in timing/developmental stage of emergence</li>
<li>life history transitions</li>
<li>growth rate</li>
<li>egg development</li>
<li>disease susceptibility</li>
<li>emergence timing</li>
</ul>
<table>
<colgroup>
<col width="21%">
<col width="15%">
<col width="21%">
<col width="42%">
</colgroup>
<thead><tr class="header">
<th>Category</th>
<th>Definition</th>
<th>Example metrics</th>
<th>Biological/Ecological importance</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Magnitude</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Frequency</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Duration</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Rate of change</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Timing</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Variability</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="temporal-variability-of-a-thermal-landscape-impacts-the-ecoystem-due-to-physiological-reactions-at-an-organismal-level" class="section level2" number="5.3">
<h2>
<span class="header-section-number">5.3</span> Temporal variability of a thermal landscape impacts the ecoystem due to physiological reactions at an organismal level<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('temporal-variability-of-a-thermal-landscape-impacts-the-ecoystem-due-to-physiological-reactions-at-an-organismal-level')" onmouseout="reset_tooltip('temporal-variability-of-a-thermal-landscape-impacts-the-ecoystem-due-to-physiological-reactions-at-an-organismal-level-tooltip')"><span class="tooltiptext" id="temporal-variability-of-a-thermal-landscape-impacts-the-ecoystem-due-to-physiological-reactions-at-an-organismal-level-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>In preparation for today’s lab you read <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/rra.3570">Wilbur, Nathan M., et al. “Characterizing physical habitat preferences and thermal refuge occupancy of brook trout (Salvelinus fontinalis) and Atlantic salmon (Salmo salar) at high river temperatures.” River Research and Applications 36.5 (2020): 769-783.</a>.</p>
<div id="ques:therm-18" class="question">
<p class="question-begin">
► Question 18
</p>
<div class="question-body">
<p>
Give a quick summary of the paper by stating the central question/hypothesis, how the question was answered (methods), key results, and key conclusions/applications.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers<span id="sol-start-13" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')"></span>
</p>
<div id="sol-body-13" class="solution-body" style="display: none;">
<ol style="list-style-type: decimal">
<li>Central Question</li>
<li>What data was collected and why? What was measured? What was it supposed to tell the scientists?</li>
<li>What where the key results?</li>
<li>What were the major conclusions? Is there a specific application? What can we do with the information we now have?</li>
</ol>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>This paper focuses on brook trout and Atlantic salmon which are considered a cold-water adapted species. In the paper, the scientists were looking at thermal anomalies (“cold spots”) that can provide thermal refugia<label for="tufte-sn-11" class="margin-toggle sidenote-number">11</label><input type="checkbox" id="tufte-sn-11" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">11</span> 1 refugium, multiple refugia</span> for brook trout during temperature anomalies. Similarly, headwater streams are important thermal refugia for salmonids which will migrate upstream during the warmer months.</p>
<p>A frequently cited reason for the importance of conserving and managing headwater streams is that they provide important climate refugia for cold-water adapted species as increasing temperatures exceed the thermal tolerance during certain times of the year.</p>
<div id="ques:therm-19" class="question">
<p class="question-begin">
► Question 19
</p>
<div class="question-body">
<p>
Outline how you could use our data set to determine whether our headwater stream continues to serve as a thermal refuge for brook trout. Be specific in terms of which metric you want to use and why. Write out the individual steps you would need to take in order to calculate that metric for our data set, don’t worry about whether or not you can turn that process into code.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>We will come up with the needed code to assess habitat suitability using the metric you have chosen and generate an appropriate summary.</p>
<div class="msmb-solution">
<p class="solution-begin">
Pointers<span id="sol-start-14" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-14', 'sol-start-14')"></span>
</p>
<div id="sol-body-14" class="solution-body" style="display: none;">
<p>The metric we decided to use is <strong>degree days</strong>, which is the number of days above or below a certain threshold during a specified time period.</p>
<p>You answer to this question should include 5-7 sentences explaining what degree days are, why they are appropriate metrics give then biological facet we are interested in and how we are going to calculate them<label for="tufte-sn-12" class="margin-toggle sidenote-number">12</label><input type="checkbox" id="tufte-sn-12" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">12</span> One distinction to make is that we did not take into account if these days are consecutive or not</span>. Be specific in your answer, e.g. why we picked the threshold, how degree days are identified.</p>
<p>This is the code we used to calculate the data</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="thermal-regimes-of-streams.html#cb25-1" aria-hidden="true" tabindex="-1"></a>crit_thresh <span class="ot">&lt;-</span> BMB <span class="sc">%&gt;%</span>                    <span class="co"># use data with hourly data</span></span>
<span id="cb25-2"><a href="thermal-regimes-of-streams.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Water_Temp <span class="sc">&gt;</span> <span class="dv">20</span>) <span class="sc">%&gt;%</span>             <span class="co"># retain only values &gt; 20</span></span>
<span id="cb25-3"><a href="thermal-regimes-of-streams.html#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(Date, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span>    <span class="co"># retain only one entry per day (even if temp was above threshold at multiple measured points)</span></span>
<span id="cb25-4"><a href="thermal-regimes-of-streams.html#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Year)                             <span class="co"># for each year count the number of days where temperature was above specified threshold</span></span></code></pre></div>
<p>Let’s take a quick look at our results</p>
<p><!--
<caption>--><span class="marginnote shownote"><span id="tab:unnamed-chunk-28">Table 5.3: </span>Number of days in a year where temperature above 20C were observed. Years with no degree days were observed are not included in this table.</span><!--</caption>--></p>
<table>
<thead><tr class="header">
<th align="right">Year</th>
<th align="right">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">2016</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">2018</td>
<td align="right">33</td>
</tr>
<tr class="odd">
<td align="right">2019</td>
<td align="right">11</td>
</tr>
<tr class="even">
<td align="right">2020</td>
<td align="right">12</td>
</tr>
</tbody>
</table>
<p>When you describe your results, keep in mind that years in which no degree days were recorded are not included in the table, so you should think of those as having a 0 value (not as missing).</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div id="ques:therm-20" class="question">
<p class="question-begin">
► Question 20
</p>
<div class="question-body">
<p>
Briefly describe your results and then discuss whether or not you think Back Mountain Brook is a suitable thermal refuge for brook trout to migrate to during warmer months.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers<span id="sol-start-15" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-15', 'sol-start-15')"></span>
</p>
<div id="sol-body-15" class="solution-body" style="display: none;">
<ul>
<li>Description Table 1: 4-6 sentences answering the following questions -
<ul>
<li>What is being summarized/compared/described?</li>
<li>What is the general pattern?</li>
<li>Are the notable details to be highlighted?</li>
<li>Is there something that should be pointed out to make sure that results are not presented in a misleading way?</li>
</ul>
</li>
<li>Discussion: State your conclusion and your arguments that support it.</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="spatial-variability-within-a-thermal-landscape-allows-aquatic-organisms-to-maximize-growth-and-survival" class="section level2" number="5.4">
<h2>
<span class="header-section-number">5.4</span> Spatial variability within a thermal landscape allows aquatic organisms to maximize growth and survival<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('spatial-variability-within-a-thermal-landscape-allows-aquatic-organisms-to-maximize-growth-and-survival')" onmouseout="reset_tooltip('spatial-variability-within-a-thermal-landscape-allows-aquatic-organisms-to-maximize-growth-and-survival-tooltip')"><span class="tooltiptext" id="spatial-variability-within-a-thermal-landscape-allows-aquatic-organisms-to-maximize-growth-and-survival-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>In addition to the temporal aspect, the <strong>thermal landscape</strong> (or <strong>thermalscape</strong>) adds a spatial component to characterize a spatially continuous temperature surface at a larger spatial scale. Back Mountain Brook is just one of many headwater streams in the Francestown/New Boston area that are all part of the same watershed.</p>
<div id="ques:therm-21" class="question">
<p class="question-begin">
► Question 21
</p>
<div class="question-body">
<p>
Briefly discuss whether or not you think that a nearby headwater stream would have the same thermal regime to Back Mountain Brook, describe parameters that might result in them exhibiting different patterns and how different you think those patterns might be.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
Pointers<span id="sol-start-16" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-16', 'sol-start-16')"></span>
</p>
<div id="sol-body-16" class="solution-body" style="display: none;">
<ul>
<li>Nearby streams should have … thermal regimes</li>
<li>Factors that could cause differences at small spatial scale include [come up with 2-3 factors based on your general knowledge and the reading assignment for each factor give us a “why”].</li>
<li>Depending on geographic proximity and factors laid out above I would expect them to be [qualify how different they might be, be specific - different patterns altogether? maybe different peak temperatures? more different in sumer? winter?]</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div id="ques:therm-22" class="question">
<p class="question-begin">
► Question 22
</p>
<div class="question-body">
<p>
Below is a code chunk that will pull in a data set of Scataquog Brook which is a nearby headwater stream. Assume that you’ve been given a limited amount of resources to preserve habitat to support local brook trout populations. Go through the steps listed below to compare the thermal regimes of the two streams to assist in deciding how to prioritize your funds.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<ol style="list-style-type: decimal">
<li>Read in the data set, briefly compare it to the <code>BMB</code> data set in terms of time frame covered and resolution, and argue whether or not you think that this is an appropriate data set to use for a comparison (3-4 sentences, make sure you support your argument).</li>
</ol>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="thermal-regimes-of-streams.html#cb26-1" aria-hidden="true" tabindex="-1"></a>SQB <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"data/SQB_water.txt"</span>, <span class="at">delim =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>,</span>
<span id="cb26-2"><a href="thermal-regimes-of-streams.html#cb26-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">col_types =</span> <span class="st">'cnn'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="thermal-regimes-of-streams.html#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date_Time =</span> <span class="fu">parse_date_time</span>(Date_Time, <span class="at">orders =</span> <span class="st">"mdyHM"</span>),</span>
<span id="cb26-4"><a href="thermal-regimes-of-streams.html#cb26-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Date =</span> <span class="fu">as_date</span>(Date_Time),</span>
<span id="cb26-5"><a href="thermal-regimes-of-streams.html#cb26-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Day =</span> <span class="fu">day</span>(Date_Time),</span>
<span id="cb26-6"><a href="thermal-regimes-of-streams.html#cb26-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">Month =</span> <span class="fu">month</span>(Date_Time),</span>
<span id="cb26-7"><a href="thermal-regimes-of-streams.html#cb26-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">Year =</span> <span class="fu">year</span>(Date_Time),</span>
<span id="cb26-8"><a href="thermal-regimes-of-streams.html#cb26-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">Hour =</span> <span class="fu">hour</span>(Date_Time))</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li><p>Calculate a series of descriptive statistics at different temporal resolutions (annual, monthly, daily) as you did for <code>BMB</code> and create at least two visualization to compare the thermal regimes of the two headwater streams<label for="tufte-sn-13" class="margin-toggle sidenote-number">13</label><input type="checkbox" id="tufte-sn-13" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">13</span> Remember, the easiest way to do this is to insert a new code chunk and just cut and paste the code from aboce and change <code>BMB</code> to <code>SQB</code></span>.</p></li>
<li><p>Compare and contrast the descriptive statistics and visualization for the two headwater streams.</p></li>
</ol>
<div class="msmb-solution">
<p class="solution-begin">
Pointers<span id="sol-start-17" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-17', 'sol-start-17')"></span>
</p>
<div id="sol-body-17" class="solution-body" style="display: none;">
<p>This is the format you used to describe your Back Mountain Brook figures. Use that as your starting point.</p>
<ul>
<li>Description figure 1: 5-7 sentences answering the following questions -
<ul>
<li>What is being summarized/compared/described?</li>
<li>What is the general pattern?</li>
<li>Are the notable details to be highlighted?</li>
<li>Is there something that should be pointed out to make sure that results are not presented in a misleading way?</li>
</ul>
</li>
<li>Description figure 2: 5-7 sentences answering the following questions -
<ul>
<li>What is being summarized/compared/described?</li>
<li>What is the general pattern?</li>
<li>Are the notable details to be highlighted?</li>
<li>Is there something that should be pointed out to make sure that results are not presented in a misleading way?</li>
</ul>
</li>
</ul>
<p>Add what you wrote above and then edit it to include the analogous description for the Scataquog data set. Make sure you state if it has the same general pattern (or not)<label for="tufte-sn-14" class="margin-toggle sidenote-number">14</label><input type="checkbox" id="tufte-sn-14" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">14</span> consider that it might share a pattern during parts of the year or it could have the same pattern but the values are shifted</span> and do the same for the notable highlights. If those are different for the Scataquog then make sure to not only state “they’re different” make sure that you point out what the notable highlights for this new data set are.</p>
<p>Finish your compare and contrast with a summary statement about how similar/different they are.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<ol start="4" style="list-style-type: decimal">
<li>Use the same metric/method you chose above to specifically focus on habitat suitability for brook trout to create a <code>SQB</code> data set and describe your results.</li>
</ol>
<div class="msmb-solution">
<p class="solution-begin">
► Solution<span id="sol-start-18" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-18', 'sol-start-18')"></span>
</p>
<div id="sol-body-18" class="solution-body" style="display: none;">
<p>You can reuse the code from above and just change <code>BMB</code> to`<code>SQB</code>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="thermal-regimes-of-streams.html#cb27-1" aria-hidden="true" tabindex="-1"></a>crit_thresh <span class="ot">&lt;-</span> SQB <span class="sc">%&gt;%</span>                    <span class="co"># use data with hourly data</span></span>
<span id="cb27-2"><a href="thermal-regimes-of-streams.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Water_Temp <span class="sc">&gt;</span> <span class="dv">20</span>) <span class="sc">%&gt;%</span>             <span class="co"># retain only values &gt; 20</span></span>
<span id="cb27-3"><a href="thermal-regimes-of-streams.html#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(Date, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span>    <span class="co"># retain only one entry per day (even if temp was above threshold at multiple measured points)</span></span>
<span id="cb27-4"><a href="thermal-regimes-of-streams.html#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Year)                             <span class="co"># for each year count the number of days where temperature was above specified threshold</span></span></code></pre></div>
<p>Let’s take a look at the results</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="thermal-regimes-of-streams.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb28-2"><a href="thermal-regimes-of-streams.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  crit_thresh,</span>
<span id="cb28-3"><a href="thermal-regimes-of-streams.html#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Number of days with recorded temperatures &gt; 20 for Scataqug Brook. The data set does not include data for 2012-2013"</span></span>
<span id="cb28-4"><a href="thermal-regimes-of-streams.html#cb28-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><!--
<caption>--><span class="marginnote shownote"><span id="tab:unnamed-chunk-32">Table 5.4: </span>Number of days with recorded temperatures &gt; 20 for Scataqug Brook. The data set does not include data for 2012-2013</span><!--</caption>--></p>
<table>
<thead><tr class="header">
<th align="right">Year</th>
<th align="right">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">2011</td>
<td align="right">30</td>
</tr>
<tr class="even">
<td align="right">2017</td>
<td align="right">5</td>
</tr>
<tr class="odd">
<td align="right">2018</td>
<td align="right">4</td>
</tr>
</tbody>
</table>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<ol start="5" style="list-style-type: decimal">
<li>Compare and contrast this metric for the two headwater streams to support your decision on which headwater stream to prioritize for habitat conservation.</li>
</ol>
<div class="msmb-solution">
<p class="solution-begin">
Pointers<span id="sol-start-19" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-19', 'sol-start-19')"></span>
</p>
<div id="sol-body-19" class="solution-body" style="display: none;">
<p>Remember, this was your format when you described the results for Back Mountain Brook.</p>
<ul>
<li>Description Table 1: 4-6 sentences answering the following questions -
<ul>
<li>What is being summarized/compared/described?</li>
<li>What is the general pattern?</li>
<li>Are the notable details to be highlighted?</li>
<li>Is there something that should be pointed out to make sure that results are not presented in a misleading way?</li>
</ul>
</li>
<li>Discussion: State your conclusion and your arguments that support it.</li>
</ul>
<p>Again make this your starting point. Add it down here, then edit it to add the information you just learned about the Scataquog<label for="tufte-sn-15" class="margin-toggle sidenote-number">15</label><input type="checkbox" id="tufte-sn-15" class="margin-toggle"><span class="sidenote"><span class="sidenote-number">15</span> Again, keep in mind that years with no observations are not included in the table. In addition, the data set does not include data for 2012 or 2013.</span>. Point out similar patterns and highlight where they differ, e.g. are number of days in the same range? Wildly different? are outlier years the same for each data set?</p>
<p>Make sure that you finish your compare &amp; contrast of the data sets with a clear conclusion about which stream you would prioritize for conservation.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>

</div>
</div>
<p style="text-align: center;">
<a href="iucn-redlist-quantifying-species-risk-levels.html"><button class="btn btn-default">Previous</button></a>
<a href="references.html"><button class="btn btn-default">Next</button></a>
</p>
<p class="build-date">Page built: 
2022-10-22
 using 
R version 4.1.2 (2021-11-01)
</p>
</div>
</div>



</body>
</html>
